// File generated by FlutterFire CLI & updated with production credentials.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVL2w6s-eog-5co4F3yBgv1IZZkp6q5rI',
    authDomain: 'stocksense-wms.firebaseapp.com',
    projectId: 'stocksense-wms',
    storageBucket: 'stocksense-wms.firebasestorage.app',
    messagingSenderId: '724162680817',
    appId: '1:724162680817:web:9b76d255378f8649c49650',
    measurementId: 'G-QH81QF8SMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVL2w6s-eog-5co4F3yBgv1IZZkp6q5rI',
    appId: '1:724162680817:android:9b76d255378f8649c49650',
    messagingSenderId: '724162680817',
    projectId: 'stocksense-wms',
    storageBucket: 'stocksense-wms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVL2w6s-eog-5co4F3yBgv1IZZkp6q5rI',
    appId: '1:724162680817:ios:9b76d255378f8649c49650',
    messagingSenderId: '724162680817',
    projectId: 'stocksense-wms',
    storageBucket: 'stocksense-wms.firebasestorage.app',
    iosBundleId: 'com.example.stocksense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVL2w6s-eog-5co4F3yBgv1IZZkp6q5rI',
    appId: '1:724162680817:ios:9b76d255378f8649c49650',
    messagingSenderId: '724162680817',
    projectId: 'stocksense-wms',
    storageBucket: 'stocksense-wms.firebasestorage.app',
    iosBundleId: 'com.example.stocksense',
  );
}
